version: "3.8"

services:
  db:
    image: postgres:14
    container_name: mini_ats_postgres
    environment:
      - POSTGRES_DB=mini_ats_db
      - POSTGRES_USER=ats_user
      - POSTGRES_PASSWORD=ats_password
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
