# Generated by Django 5.2.5 on 2025-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(choices=[('remote', 'Remote'), ('on_site', 'On Site'), ('hybrid', 'Hybrid')], default='hybrid', max_length=16),
        ),
    ]
